### ISSUE TITLE
General format options?

### ISSUE THREAD

**Issue by epage** [crate-ci/stager#21]
Currently the format is `HashMap<PathBuf, Vec<Source>>`
- Hierarchy is clear
- More complexity to expand
- More complexity to merge multiple stages (a default and a user stage)

Other possible options:
- `Vec<PathBuf, Source>`
  - Easy to expand
  - Easy to merge
  - But what do we call the `PathBuf` field in the struct (since we can't actually use a tuple)?  We we'd probably flatten the `Source` struct into this, meaning we can't conflict with any `Source` names
- `Vec<PathBuf, Vec<Source>>`
  - Worse of both worlds?

**Comment by epage** [comment]
Current format is a `Map<Path, Vec<Source>`
```toml
[[stage."/usr/bin"]]
type="SourceFile"
path="./targets/release/foo"
```

### Possible formats

`Vec<{destinaton: Path, nested: Source}>`
```toml
[[stage]]
destination="/usr/bin"
type="SourceFile"
path="./targets/release/foo"
```

Nested / Recursive which works better in yaml/json than toml
```yaml
stage:
  - name: usr
    type: Directory
    content:
      - name: bin
        type: Directory
        content:
        - type: SourceFile
          path: "./targets/release/foo"
```
